apiVersion: {{ amqstreams_api_version }}
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: {{ namespace_amqstreams_operator }}
spec:
  kafka:
    version: {{ amqstreams_supported_kafka_version }}
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '{{ amqstreams_log_message_format_version }}'
      inter.broker.protocol.version: '{{ amqstreams_inter_broker_protocol_version }}'
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator:
      watchedNamespace: {{ namespace_amqstreams_operator }}
      reconciliationIntervalSeconds: 90
    userOperator:
      watchedNamespace: {{ namespace_amqstreams_operator }}
      reconciliationIntervalSeconds: 120
